import type { WiDatepickerSize } from './wi-datepicker.types';

/** Clases compartidas del trigger (datepicker + date-range). */
export const WI_DATEPICKER_TRIGGER_BASE_CLASSES = [
  'flex',
  'w-full',
  'min-w-0',
  'items-center',
  'justify-between',
  'gap-2',
  'rounded-control',
  'border',
  'border-outline-variant',
  'bg-surface',
  'text-on-surface',
  'transition-colors',
  'outline-none',
  'cursor-pointer',
  'focus-visible:ring-2',
  'focus-visible:ring-ring',
  'focus-visible:ring-offset-2',
  'focus-visible:ring-offset-background',
  'disabled:pointer-events-none',
  'disabled:cursor-not-allowed',
  'disabled:opacity-50',
  'aria-invalid:border-error',
  'aria-invalid:focus-visible:ring-error',
  'data-[placeholder]:text-on-surface-variant',
].join(' ');

export const WI_DATEPICKER_TRIGGER_SIZE_CLASSES: Record<WiDatepickerSize, string> = {
  sm: 'h-control-sm px-3 text-sm',
  md: 'h-control-md px-3 text-sm',
  lg: 'h-control-lg px-4 text-base',
};

export const WI_DATEPICKER_PANEL_CLASSES = [
  'z-50',
  'w-fit',
  'overflow-hidden',
  'rounded-control',
  'border',
  'border-outline-variant',
  'bg-surface',
  'text-on-surface',
  'shadow-md',
  'p-3',
].join(' ');

/** Variantes `data-[…=true]` alineadas con BrnCalendarCellButton / Helm (single + range). */
export const WI_DATEPICKER_DAY_BUTTON_CLASSES = [
  'inline-flex',
  'size-8',
  'items-center',
  'justify-center',
  'rounded-control',
  'text-sm',
  'outline-none',
  'cursor-pointer',
  'transition-colors',
  'hover:bg-surface-variant',
  'focus-visible:ring-2',
  'focus-visible:ring-ring',
  'data-[outside=true]:text-on-surface-variant',
  'data-[outside=true]:opacity-60',
  'data-[today=true]:border',
  'data-[today=true]:border-outline-variant',
  'data-[selected-single=true]:bg-primary',
  'data-[selected-single=true]:text-on-primary',
  'data-[selected-single=true]:hover:bg-primary',
  'data-[range-start=true]:bg-primary',
  'data-[range-start=true]:text-on-primary',
  'data-[range-start=true]:hover:bg-primary',
  'data-[range-end=true]:bg-primary',
  'data-[range-end=true]:text-on-primary',
  'data-[range-end=true]:hover:bg-primary',
  'data-[range-middle=true]:bg-primary-container',
  'data-[range-middle=true]:text-on-primary-container',
  'data-[range-middle=true]:rounded-none',
  'data-[disabled=true]:pointer-events-none',
  'data-[disabled=true]:opacity-40',
].join(' ');

export const WI_DATEPICKER_NAV_BUTTON_CLASSES = [
  'inline-flex',
  'size-8',
  'items-center',
  'justify-center',
  'rounded-control',
  'text-on-surface',
  'outline-none',
  'cursor-pointer',
  'hover:bg-surface-variant',
  'focus-visible:ring-2',
  'focus-visible:ring-ring',
  'disabled:pointer-events-none',
  'disabled:opacity-40',
].join(' ');

export const WI_DATEPICKER_TIME_INPUT_CLASSES = [
  'h-control-sm',
  'w-12',
  'rounded-control',
  'border',
  'border-outline',
  'bg-surface',
  'px-1',
  'text-center',
  'text-sm',
  'text-on-surface',
  'outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-ring',
  'disabled:cursor-not-allowed',
  'disabled:opacity-50',
].join(' ');
